### PR TITLE
Encrypt tor privatekey 2

### PR DESCRIPTION
**Pull request by orbitalturtle**
Hey @gkrizek ! This PR addresses some of the comments from LL on your encrypt-tor-privatekey PR. 

I think it's pulling in hundreds of other commits because my branch is rebased on top of master. *thinking emoji* If you wouldn't mind rebasing your branch on top of master, then I think it'll show a cleaner diff of the changes I made to your PR! Anyway, I don't think the diff will look super different, since most of the changes are just changing up the commit structure

### CODE REVIEW

**Comment by gkrizek** [comment]
Awesome, thanks for doing this @orbitalturtle ! This looks great. You're right, not too much different. So this resolved all of Oli's comments in the original PR? I think this is good to go!

However, it looks like Git really doesn't like this. I wonder if it's best for me to just locally overwrite my branch with yours instead of trying to merge.

**Comment by orbitalturtle** [comment]
@gkrizek Awesome, let me do one more run through of Oli's comments as well as the comments from the other reviews way earlier just to make sure we got everything.

And re: the git conflict, ahh sure that makes sense. I can quickly try and fix the conflict today but if it doesn't work, that sounds good to me

**Comment by orbitalturtle** [comment]
Lol I think I fixed the conflict but managed to somehow lose one of your commits x_x; Will update once I figure that out

**Comment by orbitalturtle** [comment]
@gkrizek Nevermind, I think my attempts at fixing the conflicts failed lol if you want to try your idea. 

Otherwise, I think this PR is good now (as long as the returnKey change I mentioned in Slack is okay). I also just added one last commit that updates the docs, since that's one of the required CI checks 

Also, once you change the PR, if you could resolve all the comments from oli, wilmer etc in the PR, that would be wonderful! Thanks ~ apparently I can't resolve them since I'm not the PR creator

**Comment by gkrizek** [comment]
Sounds good. I'll do that! All looks good and after a second look I think you handled the return key thing correctly.

**Pull request merged**
